if(EXISTS "/Users/whisper/.zenflow/worktrees/frontend-beta-b995/build_test/test_integration[1]_tests.cmake")
  include("/Users/whisper/.zenflow/worktrees/frontend-beta-b995/build_test/test_integration[1]_tests.cmake")
else()
  add_test(test_integration_NOT_BUILT test_integration_NOT_BUILT)
endif()
